#!/usr/bin/env node
// ===========================================================
// 🍎 scripts/make-app.js — a double-clickable launcher for macOS
// ===========================================================
//   npm run shortcut
//
// Puts a "Desktop Pet.app" on your desktop. Double-click it and the pet starts
// with no Terminal window anywhere — the bundle's executable is a two-line
// script that hands straight over to Electron, and macOS launches an .app as a
// GUI program with nothing attached to it.
//
// Drag it into /Applications, or keep it in the Dock, and it behaves like any
// other background app: an icon to click, and the menu bar icon by the clock
// to show, hide and quit.
//
// It points at Electron and at this folder, so keep the folder where it is —
// if you move it, run `npm run shortcut` again. macOS only; on Windows,
// scripts/make-shortcut.js does the same job with a .lnk.
// ===========================================================

const fs = require('fs');
const os = require('os');
const path = require('path');

const APP_DIR = path.join(__dirname, '..');
const BUNDLE_NAME = 'Desktop Pet.app';
// Also our marker: a bundle without this exact executable isn't one of ours,
// and never gets overwritten.
const EXECUTABLE = 'desktop-pet';

// POSIX single-quoting: everything is literal inside '…', and the only thing
// that can't appear is a quote itself, which ends the string and comes back as
// '\''. Handles the spaces and apostrophes real folder names contain.
function shQuote(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

function xmlEscape(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function buildLauncher(electronPath, appDir) {
  return [
    '#!/bin/sh',
    '# Generated by `npm run shortcut` — run it again to point this somewhere else.',
    `exec ${shQuote(electronPath)} ${shQuote(appDir)}`,
    '',
  ].join('\n');
}

function buildPlist({ version, icon }) {
  const entries = [
    ['CFBundleName', 'Desktop Pet'],
    ['CFBundleDisplayName', 'Desktop Pet'],
    ['CFBundleIdentifier', 'com.mygameindie.computerpet.launcher'],
    ['CFBundleExecutable', EXECUTABLE],
    ['CFBundlePackageType', 'APPL'],
    ['CFBundleShortVersionString', version],
    ['CFBundleVersion', version],
  ];
  if (icon) entries.push(['CFBundleIconFile', icon]);

  const body = entries
    .map(([key, value]) => `  <key>${key}</key>\n  <string>${xmlEscape(value)}</string>`)
    .join('\n');

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    '<dict>',
    body,
    // A background app: no Dock icon for the launcher, no ⌘-Tab entry. The pet
    // lives in the menu bar.
    '  <key>LSUIElement</key>',
    '  <true/>',
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

// Electron ships its own icon; borrowing it beats a blank bundle. Returns the
// CFBundleIconFile name, or null if it isn't where it usually is.
function copyIcon(electronPath, resourcesDir) {
  // …/Electron.app/Contents/MacOS/Electron → …/Electron.app/Contents/Resources
  const source = path.join(path.dirname(path.dirname(electronPath)), 'Resources', 'electron.icns');
  try {
    fs.mkdirSync(resourcesDir, { recursive: true });
    fs.copyFileSync(source, path.join(resourcesDir, 'app.icns'));
    return 'app';
  } catch (_) {
    return null;
  }
}

function makeMacApp() {
  let electronPath;
  try {
    electronPath = require('electron');
  } catch (_) { /* not installed */ }

  if (typeof electronPath !== 'string' || !electronPath) {
    console.error('Electron is not installed yet. Run `npm install` in this folder first.');
    process.exit(1);
  }

  const desktop = path.join(os.homedir(), 'Desktop');
  const parent = fs.existsSync(desktop) ? desktop : os.homedir();
  const bundle = path.join(parent, BUNDLE_NAME);

  // Replacing our own launcher is the point; deleting anything else that
  // happens to share the name — a real build someone dragged here — is not.
  if (fs.existsSync(bundle)) {
    if (!fs.existsSync(path.join(bundle, 'Contents', 'MacOS', EXECUTABLE))) {
      console.error(`There is already something called "${BUNDLE_NAME}" at ${parent},`);
      console.error('and it was not made by this script, so it has been left alone.');
      console.error('Move or rename it, then run `npm run shortcut` again.');
      process.exit(1);
    }
    fs.rmSync(bundle, { recursive: true, force: true });
  }

  const contents = path.join(bundle, 'Contents');
  const macos = path.join(contents, 'MacOS');
  fs.mkdirSync(macos, { recursive: true });

  const icon = copyIcon(electronPath, path.join(contents, 'Resources'));

  let version = '1.0.0';
  try {
    version = require('../package.json').version || version;
  } catch (_) { /* keep the default */ }

  fs.writeFileSync(path.join(contents, 'Info.plist'), buildPlist({ version, icon }));
  // 0o755: macOS refuses to launch a bundle whose executable isn't executable.
  fs.writeFileSync(path.join(macos, EXECUTABLE), buildLauncher(electronPath, APP_DIR), { mode: 0o755 });
  fs.chmodSync(path.join(macos, EXECUTABLE), 0o755);

  console.log(`Created: ${bundle}`);
  console.log('Double-click it to start the pet with no Terminal window.');
  console.log('Drag it to /Applications or the Dock if you want it handy.');
  console.log('The menu bar icon by the clock shows, hides and quits the pet.');
}

if (require.main === module) {
  if (process.platform !== 'darwin') {
    console.log('This is a macOS-only helper.');
    console.log('On Windows, use: npm run shortcut (scripts/make-shortcut.js)');
    console.log('On Linux, use: npm run start:bg');
  } else {
    makeMacApp();
  }
}

module.exports = { makeMacApp, buildLauncher, buildPlist, shQuote };
